services:
  postgres:
    image: 14.19-alpine3.21
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - pharmatic-network


  chembl-mcp-server:
    build:
      context: ../MCP-serveres/ChEMBL-MCP-Server
      dockerfile: Dockerfile
    image: mhalainekm/chembl-mcp-server:${VERSION_CHEMBL_MCP_SERVER}
    container_name: chembl-mcp-server
    ports:
      - "3000:3000"
    restart: no
    networks:
      - pharmatic-network
    volumes:
      - ./ChEMBL-MCP-Server-main:/app
    

  pharma-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-pharmamind:0.1.0-mini-dev
    container_name: mini-pharmamind-app-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DEEPSEEK_API=${DEEPSEEK_API}
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=${ENVIRONMENT}
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      chembl-mcp-server:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./orchestration:/app/orchestration
      - ./agents:/app/agents
      - ./config:/app/config
      - ./tools:/app/tools
      - ./session_state:/app/session_state
      - ./session_history:/app/session_history
      - ./databases:/app/databases
      - ./utilities:/app/utilities
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - pharmatic-network



networks:
  pharmatic-network:
    driver: bridge
  
volumes:
  postgres_data:
    name: agentic-pharma-postgres-data
